# ===========
#   PLUGINS
# ===========
# package manager
set -g @plugin 'tmux-plugins/tpm'
# sensible default settings
set -g @plugin 'tmux-plugins/tmux-sensible'
# status bar
set -g @plugin 'fabioluciano/tmux-powerkit'
# easy copy/paste
set -g @plugin 'tmux-plugins/tmux-yank'
# save/restore sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
# automatically save/restore sessions
set -g @plugin 'tmux-plugins/tmux-continuum'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# remap prefix from 'C-b' to 'C-Space'
unbind C-b  
set-option -g prefix C-Space  
bind-key C-Space send-prefix

# enable mouse control (clickable windows, panes, resizable panes)  
set -g mouse on

# Enable 24-bit color support
set-option -sa terminal-overrides ",xterm*:Tc"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows
set -g renumber-windows on

# Vi mode
set-window-option -g mode-keys vi

# Vim-style copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Disable bell?
set -g bell-action none

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
